[update root] move current version to 2.6.0 subdir
In order to be able to update the root website, we need to be able to
build the root website. This means that we need, at a minimum, two
separate versions of the docs editable and buildable at the same time:
the "next" version, on which most of the work happens, and the "current"
version, on which we may want to make occasional adjustments.

Right now the "next" version is 2.6.0 and the "current" one is 2.5.1.

However, giving the docs repo the ability to update root essentially
forces it to take over root updates generally, which means we'll benefit
from being able to build more than just the last two versions. More on
that later.

For the time being, this PR moves the next version under a subfolder;
the current version will be added as a subsequent PR, and then (as yet
another PR) I'll add the root update itself.

For most of the work, which touches only the next version, this should
be a very minimal disruption as all it changes is the work happens in a
nested folder, but everything stays the same.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,7 +18,7 @@ commands:
         command: |
           set -euo pipefail
 
-          git log -n1 --format=%H nix shell.nix > /tmp/nix-cache-key
+          git log -n1 --format=%H nix shell.nix docs/*/nix docs/*/shell.nix > /tmp/nix-cache-key
           sudo mkdir /nix
           sudo chown $USER /nix
     - restore_cache:
@@ -41,7 +41,13 @@ commands:
 
          sh <(curl -fsSL https://nixos.org/nix/install) --no-daemon
          . /home/circleci/.nix-profile/etc/profile.d/nix.sh
-         nix-shell shell.nix --run 'echo "Done loading all packages."'
+         nix-shell shell.nix --run 'echo "Done loading all root packages."'
+         cd docs
+         for v in *; do
+             cd $v
+             nix-shell shell.nix --pure --run 'echo "Done loading all packages in $v."'
+             cd -
+         done
     - save_cache:
         key: nix-{{ checksum "/tmp/nix-cache-key" }}
         paths:
@@ -58,21 +64,14 @@ commands:
         command: |
           set -euo pipefail
           . /home/circleci/.nix-profile/etc/profile.d/nix.sh
-          nix-shell shell.nix \
-            --pure \
-            --run bash \<<'EOF'
-            set -euo pipefail
-
-            python3 -m venv .python-env
-            source .python-env/bin/activate
-            python -m pip install -r requirements.txt
-            git clone https://github.com/bame-da/sphinx-external-toc.git
-            cd sphinx-external-toc
-            git checkout 8a33082711c7ccf3472a9381f9c9eee474f71a2d
-            flit install
-            cd ..
-            rm -rf sphinx-external-toc
-          EOF
+          cd docs
+          for v in *; do
+              cd $v
+              if [ -f bin/setup-python ]; then
+                  nix-shell shell.nix --pure --run "bin/setup-python"
+              fi
+              cd -
+          done
 
 jobs:
   build_docs:
@@ -92,22 +91,24 @@ jobs:
 
            mkdir -p /tmp/workspace
 
-           nix-shell shell.nix \
-             --pure \
-             --keep ARTIFACTORY_USERNAME \
-             --keep ARTIFACTORY_PASSWORD \
-             --run bash \<<'EOF'
-             set -euo pipefail
-             source .python-env/bin/activate
-             PATH="$(pwd)/.python-env/bin:$PATH"
-             prefix=$(jq -r '.prefix' versions.json)
-             if [[ ${#prefix} -lt 5 ]]; then
-               echo "Pushhing to $prefix is not currently supported."
-               exit 1
-             fi
-             bin/build
-             mv workdir/target/html-docs-*.tar.gz /tmp/workspace/
+           cd docs
+           for v in *; do
+               cd $v
+               nix-shell shell.nix \
+                 --pure \
+                 --keep ARTIFACTORY_USERNAME \
+                 --keep ARTIFACTORY_PASSWORD \
+                 --run bash \<<'EOF'
+                   set -euo pipefail
+                   if [ -f .python-env/bin/activate ]; then
+                       source .python-env/bin/activate
+                       PATH="$(pwd)/.python-env/bin:$PATH"
+                   fi
+                   bin/build
            EOF
+               mv workdir/target/html-$v.tar.gz /tmp/workspace
+               cd -
+           done
       - store_artifacts:
          path: /tmp/workspace
       - persist_to_workspace:
@@ -138,18 +139,20 @@ jobs:
              --run bash \<<'EOF'
              set -euo pipefail
 
-             prefix=$(jq -r '.prefix' versions.json)
-             sdk_version=$(jq -r '.daml' versions.json)
-             if [[ ${#prefix} -lt 5 ]]; then
-               echo "Pushhing to $prefix is not currently supported."
-               exit 1
-             fi
-
-             upload=$(mktemp -d)
-             tar xf /tmp/workspace/html-docs-$sdk_version.tar.gz -C $upload --strip-components=1
-             aws s3 rm s3://docs-daml-com/$prefix --recursive --region us-east-1
-             aws s3 cp $upload s3://docs-daml-com/$prefix --recursive --acl public-read --region us-east-1
-             aws cloudfront create-invalidation --distribution-id E1U753I56ERH55 --paths "/$prefix/*"
+             cd docs
+             for v in *; do
+                 sha=$(git log -n1 --format=%H $v)
+                 if [ "$(curl https://docs.daml.com/$v/sha)" = "$sha" ]; then
+                     echo "$v is up-to-date, nothing to do."
+                 else
+                     echo "updating $v to $sha."
+                     upload=$(mktemp -d)
+                     tar xf /tmp/workspace/html-$v.tar.gz -C $upload --strip-components=1
+                     echo $sha > $upload/sha
+                     aws s3 rm s3://docs-daml-com/$v --recursive --region us-east-1
+                     aws s3 cp $upload s3://docs-daml-com/$v --recursive --acl public-read --region us-east-1
+                     aws cloudfront create-invalidation --distribution-id E1U753I56ERH55 --paths "/$v/*"
+             done
            EOF
 
   publish_snapshots:
@@ -176,9 +179,6 @@ jobs:
              --keep AWS_SECRET_ACCESS_KEY \
              --run bash \<<'EOF'
              set -euo pipefail
-             source .python-env/bin/activate
-             PATH="$(pwd)/.python-env/bin:$PATH"
-
              snapshots=$(curl -sf https://docs.daml.com/snapshots.json \
                         | jq -r '
                                 # The snapshots.json file is a map of version to version.
@@ -228,37 +228,51 @@ jobs:
                  elif [ "$version" = "2.0.1-snapshot.20220419.9374.0.44df8f12" ] \
                    || [ "$version" = "2.1.0-snapshot.20220411.9707.0.f6fed6ea" ] \
                    || [ "$version" = "2.5.0-snapshot.20221010.10736.0.2f453a14" ]
-                 then echo "-> Skipping, known broken."
+                 then echo " -> Skipping, known broken."
                  else
-                     echo "-> Getting Canton version"
-                     canton=$(curl -H "Authorization: bearer $GITHUB_TOKEN" \
-                                   --fail \
-                                   --silent \
-                                   https://api.github.com/graphql \
-                                   -XPOST \
-                                   -d"$(jq -n --arg q "$(graphql $version)" '{query: $q}')" \
-                            | jq -r '.data.repository.release.releaseAssets.nodes[].name' \
-                            | grep canton \
-                            | head -1 \
-                            | sed 's/canton-open-source-\(.*\)\.tar\.gz/\1/')
-                     finance=$(git show origin/main:versions.json | jq -r '.daml_finance')
-                     echo "-> Building daml $version with canton $canton & finance $finance."
-                     jq -n \
-                        --arg daml $version \
-                        --arg canton $canton \
-                        --arg finance $finance \
-                        '{daml: $daml, canton: $canton, prefix: $daml, daml_finance: $finance}' \
-                        > versions.json
-
-                     bin/clean
-                     bin/build
-                     upload=$(mktemp -d)
-                     tar xf workdir/target/html-docs-$version.tar.gz -C $upload --strip-components=1
-                     aws s3 cp $upload s3://docs-daml-com/$version --recursive --acl public-read --region us-east-1
-                     aws cloudfront create-invalidation --distribution-id E1U753I56ERH55 --paths "/$version/*"
-                     echo "-> Done."
+                     base=${version%-*}
+                     if [ -d docs/$base ]; then
+                         (
+                             cd docs/$base
+                             echo " -> Getting Canton version"
+                             canton=$(curl -H "Authorization: bearer $GITHUB_TOKEN" \
+                                           --fail \
+                                           --silent \
+                                           https://api.github.com/graphql \
+                                           -XPOST \
+                                           -d"$(jq -n --arg q "$(graphql $version)" '{query: $q}')" \
+                                    | jq -r '.data.repository.release.releaseAssets.nodes[].name' \
+                                    | grep canton \
+                                    | head -1 \
+                                    | sed 's/canton-open-source-\(.*\)\.tar\.gz/\1/')
+                             echo "-> Building daml $version with canton $canton & finance $finance."
+                             tmp=$(mktemp)
+                             jq --arg daml $version \
+                                --arg canton $canton \
+                                '.daml |= $daml | .canton |= $canton' \
+                                versions.json \
+                                > $tmp
+                             mv $tmp versions.json
+                             nix-shell shell.nix --pure --run bash \<<'NIX'
+                                 set euo pipefail
+                                 if [ -f .python-env/bin/activate ]; then
+                                     source .python-env/bin/activate
+                                     PATH="$(pwd)/.python-env/bin:$PATH"
+                                 fi
+                                 bin/clean
+                                 bin/build
+           NIX
+                             upload=$(mktemp -d)
+                             tar xf workdir/target/html-$base.tar.gz -C $upload --strip-components=1
+                             aws s3 cp $upload s3://docs-daml-com/$version --recursive --acl public-read --region us-east-1
+                             aws cloudfront create-invalidation --distribution-id E1U753I56ERH55 --paths "/$version/*"
+                             echo "-> Done."
+                         )
+                     else
+                         echo " -> No base version $base found for $version, unable to proceed."
+                         exit 1
+                     fi
                  fi
-                 echo
              done
            EOF
 
