[update-root] final step: refresh root to 2.5.1 (#142)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -109,6 +109,9 @@ jobs:
                mv workdir/target/html-$v.tar.gz /tmp/workspace
                cd -
            done
+           cd ..
+           root=$(cat root)
+           bin/check-root $root
       - store_artifacts:
          path: /tmp/workspace
       - persist_to_workspace:
@@ -139,10 +142,12 @@ jobs:
              --run bash \<<'EOF'
              set -euo pipefail
 
+             root=$(cat root)
              cd docs
              for v in *; do
                  sha=$(git log -n1 --format=%H $v)
-                 if [ "$(curl https://docs.daml.com/$v/sha)" = "$sha" ]; then
+                 if ([ "$(curl https://docs.daml.com/$v/sha)" = "$sha" ] && [ "$v" != "$root" ]) \
+                  || ([ "$v" == "$root" ] && [ "$(curl https://docs.daml.com/sha)" == "$sha" ]); then
                      echo "$v is up-to-date, nothing to do."
                  else
                      echo "updating $v to $sha."
@@ -150,10 +155,36 @@ jobs:
                      tar xf /tmp/workspace/html-$v.tar.gz -C $upload --strip-components=1
                      echo $sha > $upload/sha
                      aws s3 rm s3://docs-daml-com/$v --recursive --region us-east-1
-                     aws s3 cp $upload s3://docs-daml-com/$v --recursive --acl public-read --region us-east-1
+                     aws s3 cp $upload s3://docs-daml-com/$v --recursive --acl public-read --region us-east-1 --no-progress
                      aws cloudfront create-invalidation --distribution-id E1U753I56ERH55 --paths "/$v/*"
                  fi
              done
+             cd ..
+             bin/check-root $root
+             sha=$(git log -n1 --format=%H docs/$root)
+             if [ "$(curl https://docs.daml.com/sha)" = "$sha" ]; then
+                 echo "root is up-to-date ($root, $sha), nothing to do."
+             else
+                 echo "updating root to $root (sha: $sha)"
+                 echo " -> creating local folder"
+                 upload=$(mktemp -d)
+                 tar xf /tmp/workspace/html-$root.tar.gz -C $upload --strip-components=1
+                 echo $sha > $upload/sha
+                 cat dropdown_versions | sed 's/\(.*\)/"\1"/' | jq -sc '[.[] | {(.): .} ] | add' > $upload/versions.json
+                 bin/list-hidden-versions > $upload/snapshots.json
+                 cp root $upload/latest
+                 echo " -> removing old version"
+                 for f in $(aws s3 ls s3://docs-daml-com/ \
+                            | grep -oP '(?<=.{30} ).*' \
+                            | grep -v '^[0-9]' \
+                            | grep -v '^daml-driver-for-postgresql/$'); do
+                     aws s3 rm s3://docs-daml-com/$f --recursive --region us-east-1
+                 done
+                 echo " -> pushing new version"
+                 aws s3 cp $upload s3://docs-daml-com/ --recursive --acl public-read --region us-east-1 --no-progress
+                 echo " -> invalidating cache"
+                 aws cloudfront create-invalidation --distribution-id E1U753I56ERH55 --paths "/*"
+             fi
            EOF
 
   publish_snapshots:
@@ -265,7 +296,7 @@ jobs:
            NIX
                              upload=$(mktemp -d)
                              tar xf workdir/target/html-$base.tar.gz -C $upload --strip-components=1
-                             aws s3 cp $upload s3://docs-daml-com/$version --recursive --acl public-read --region us-east-1
+                             aws s3 cp $upload s3://docs-daml-com/$version --recursive --acl public-read --region us-east-1 --no-progress
                              aws cloudfront create-invalidation --distribution-id E1U753I56ERH55 --paths "/$version/*"
                              echo "-> Done."
                          )
